import type { ImpactId } from "@/lib/mood";

// One canonical spelling per feeling. The family only supplies default impacts;
// related-word discovery uses overlapping groups below, not a single parent.
// Valence is an editorial browsing hint, never a limit on what someone can select.
export const feelingFamilies = {
  despair: {
    impacts: ["school", "health", "identity", "work"],
    words: [
      ["Hopeless", -95],
      ["Helpless", -85],
      ["Defeated", -82],
      ["Powerless", -80],
      ["Empty", -70],
      ["Lost", -60],
      ["Discouraged", -52],
      ["Despairing", -94],
      ["Despondent", -86],
      ["Desolate", -88],
      ["Crushed", -90],
      ["Shattered", -94],
      ["Brokenhearted", -91],
      ["Demoralized", -76],
      ["Disheartened", -64],
      ["Downtrodden", -72],
      ["Beaten down", -78],
      ["Trapped", -74],
      ["Stuck", -46],
      ["Cornered", -66],
      ["Deflated", -48],
      ["Resigned", -44],
      ["Pessimistic", -42],
      ["Bleak", -68],
      ["Crestfallen", -62],
      ["Abandoned", -82],
      ["Forsaken", -86],
    ],
  },
  grief: {
    impacts: ["family", "friends", "partner", "dating"],
    words: [
      ["Devastated", -96],
      ["Heartbroken", -92],
      ["Grieving", -88],
      ["Homesick", -38],
      ["Bereft", -86],
      ["Sorrowful", -74],
      ["Mournful", -76],
      ["Inconsolable", -94],
      ["Anguished", -90],
      ["Aching", -64],
      ["Heartsick", -78],
      ["Longing", -32],
      ["Yearning", -26],
      ["Missing someone", -48],
      ["Lovesick", -44],
      ["Unmoored", -62],
      ["Hollow", -68],
      ["Bereaved", -88],
      ["In shock", -72],
      ["Gutted", -88],
      ["Dismayed", -64],
    ],
  },
  sadness: {
    impacts: ["friends", "family", "partner", "school"],
    words: [
      ["Miserable", -90],
      ["Sad", -66],
      ["Hurt", -62],
      ["Disappointed", -50],
      ["Down", -46],
      ["Gloomy", -40],
      ["Sensitive", -24],
      ["Wistful", -10],
      ["Unhappy", -58],
      ["Upset", -60],
      ["Melancholy", -44],
      ["Blue", -40],
      ["Low", -42],
      ["Tearful", -56],
      ["Dejected", -60],
      ["Downhearted", -54],
      ["Heavyhearted", -66],
      ["Let down", -56],
      ["Saddened", -58],
      ["Somber", -36],
      ["Forlorn", -68],
      ["Tender", -8],
      ["Vulnerable", -30],
      ["Raw", -52],
      ["Fragile", -48],
      ["Weepy", -48],
      ["Glum", -38],
      ["Doleful", -54],
      ["Sullen", -44],
      ["Regretful", -52],
    ],
  },
  fear: {
    impacts: ["school", "health", "money", "news"],
    words: [
      ["Terrified", -92],
      ["Panicked", -86],
      ["Scared", -68],
      ["Anxious", -60],
      ["Worried", -48],
      ["Nervous", -35],
      ["Uneasy", -28],
      ["Afraid", -66],
      ["Frightened", -72],
      ["Alarmed", -64],
      ["Apprehensive", -44],
      ["Dreading", -66],
      ["Freaked out", -78],
      ["Petrified", -94],
      ["Horrified", -92],
      ["Threatened", -78],
      ["Unsafe", -76],
      ["On edge", -52],
      ["Jittery", -38],
      ["Edgy", -36],
      ["Tense", -44],
      ["Shaky", -48],
      ["Unsettled", -38],
      ["Rattled", -54],
      ["Startled", -30],
      ["Spooked", -42],
      ["Wary", -26],
      ["Guarded", -24],
      ["Cautious", -8],
      ["Suspicious", -36],
      ["Distrustful", -44],
      ["Daunted", -50],
      ["Intimidated", -54],
      ["Fretful", -46],
      ["Concerned", -34],
      ["Timid", -22],
    ],
  },
  anger: {
    impacts: ["friends", "family", "school", "work"],
    words: [
      ["Furious", -88],
      ["Disgusted", -72],
      ["Angry", -68],
      ["Resentful", -58],
      ["Frustrated", -55],
      ["Jealous", -50],
      ["Irritated", -38],
      ["Annoyed", -30],
      ["Mad", -62],
      ["Livid", -90],
      ["Enraged", -92],
      ["Outraged", -84],
      ["Fuming", -80],
      ["Seething", -82],
      ["Indignant", -60],
      ["Aggravated", -48],
      ["Exasperated", -52],
      ["Irate", -74],
      ["Bitter", -62],
      ["Hostile", -70],
      ["Spiteful", -66],
      ["Vengeful", -78],
      ["Provoked", -56],
      ["Offended", -50],
      ["Insulted", -56],
      ["Betrayed", -82],
      ["Cheated", -68],
      ["Wronged", -64],
      ["Fed up", -54],
      ["Irritable", -40],
      ["Cranky", -32],
      ["Grumpy", -28],
      ["Sour", -36],
      ["Envious", -44],
      ["Possessive", -42],
      ["Defensive", -36],
      ["Appalled", -78],
      ["Repulsed", -76],
      ["Revolted", -80],
      ["Disapproving", -32],
      ["Contemptuous", -62],
    ],
  },
  shame: {
    impacts: ["identity", "friends", "school", "dating"],
    words: [
      ["Ashamed", -84],
      ["Guilty", -60],
      ["Embarrassed", -50],
      ["Insecure", -48],
      ["Self-conscious", -34],
      ["Awkward", -26],
      ["Humiliated", -86],
      ["Mortified", -80],
      ["Remorseful", -68],
      ["Self-critical", -46],
      ["Inadequate", -60],
      ["Inferior", -58],
      ["Unworthy", -72],
      ["Exposed", -48],
      ["Judged", -54],
      ["Small", -52],
      ["Foolish", -40],
      ["Sheepish", -28],
      ["Flustered", -30],
      ["Bashful", -10],
      ["Shy", -8],
      ["Uncomfortable", -34],
      ["Unlovable", -76],
      ["Unwanted", -72],
      ["Unattractive", -50],
      ["Uncertain of myself", -40],
      ["Disappointed in myself", -58],
      ["Contrite", -54],
      ["Self-doubting", -44],
      ["Out of place", -42],
    ],
  },
  stress: {
    impacts: ["school", "work", "tasks", "money"],
    words: [
      ["Overwhelmed", -76],
      ["Stressed", -58],
      ["Pressured", -42],
      ["Rushed", -32],
      ["Impatient", -26],
      ["Restless", -24],
      ["Busy", -6],
      ["Under pressure", -52],
      ["Overloaded", -66],
      ["Swamped", -60],
      ["Overextended", -62],
      ["Stretched thin", -58],
      ["Overburdened", -68],
      ["Frazzled", -58],
      ["Frantic", -72],
      ["Overstimulated", -60],
      ["Wound up", -42],
      ["Fidgety", -24],
      ["Antsy", -22],
      ["Unprepared", -44],
      ["Out of control", -74],
      ["Suffocated", -76],
      ["Weighed down", -56],
      ["Preoccupied", -20],
      ["Pulled in every direction", -60],
      ["On the spot", -38],
      ["Hassled", -42],
      ["Harried", -48],
      ["Agitated", -54],
      ["Troubled", -48],
      ["Unfocused", -26],
    ],
  },
  tiredness: {
    impacts: ["sleep", "health", "school", "fitness"],
    words: [
      ["Exhausted", -72],
      ["Burnt out", -68],
      ["Drained", -56],
      ["Tired", -32],
      ["Sluggish", -24],
      ["Sleepy", -10],
      ["Worn out", -62],
      ["Wiped out", -64],
      ["Spent", -58],
      ["Depleted", -62],
      ["Fatigued", -52],
      ["Weary", -48],
      ["Run-down", -50],
      ["Drowsy", -16],
      ["Groggy", -28],
      ["Foggy", -30],
      ["Heavy", -40],
      ["Lethargic", -38],
      ["Listless", -36],
      ["Sapped", -54],
      ["Overworked", -60],
      ["Mentally exhausted", -70],
      ["Emotionally drained", -72],
      ["Fried", -58],
      ["Low-energy", -24],
      ["Under the weather", -44],
      ["Unwell", -52],
      ["Sick", -58],
      ["Achy", -44],
      ["Sore", -30],
      ["Rested", 32],
      ["Well-rested", 46],
      ["Recharged", 50],
      ["Restored", 52],
    ],
  },
  disconnection: {
    impacts: ["friends", "family", "community", "dating"],
    words: [
      ["Isolated", -80],
      ["Lonely", -74],
      ["Rejected", -70],
      ["Left out", -52],
      ["Withdrawn", -40],
      ["Disconnected", -36],
      ["Detached", -14],
      ["Alone", -48],
      ["Invisible", -66],
      ["Ignored", -58],
      ["Overlooked", -52],
      ["Unseen", -60],
      ["Unheard", -58],
      ["Misunderstood", -52],
      ["Alienated", -68],
      ["Estranged", -64],
      ["Excluded", -62],
      ["Shut out", -66],
      ["Unwelcome", -58],
      ["Unsupported", -64],
      ["Unappreciated", -54],
      ["Neglected", -72],
      ["Distant", -30],
      ["Closed off", -36],
      ["Dismissed", -56],
      ["Invalidated", -62],
      ["Disregarded", -50],
      ["Adrift", -48],
      ["Out of sync", -26],
      ["Displaced", -54],
      ["Socially drained", -44],
    ],
  },
  flatness: {
    impacts: ["tasks", "phone", "hobbies", "school"],
    words: [
      ["Numb", -64],
      ["Apathetic", -40],
      ["Unmotivated", -30],
      ["Bored", -22],
      ["Indifferent", -6],
      ["Flat", -28],
      ["Blah", -20],
      ["Meh", -8],
      ["Dull", -24],
      ["Uninspired", -28],
      ["Disengaged", -32],
      ["Checked out", -38],
      ["Uninterested", -22],
      ["Unfulfilled", -48],
      ["Unsatisfied", -38],
      ["Unenthusiastic", -24],
      ["Stagnant", -36],
      ["Aimless", -32],
      ["Directionless", -40],
      ["Emotionless", -34],
      ["Blank", -16],
      ["Dazed", -26],
      ["Spaced out", -18],
      ["Absent-minded", -12],
      ["Unmoved", -4],
      ["Neutral", 0],
      ["Okay", 4],
      ["Fine", 6],
      ["So-so", -2],
      ["Detached from myself", -46],
    ],
  },
  uncertainty: {
    impacts: ["school", "identity", "dating", "work"],
    words: [
      ["Confused", -28],
      ["Torn", -22],
      ["Distracted", -18],
      ["Uncertain", -16],
      ["Ambivalent", -6],
      ["Unsure", -18],
      ["Conflicted", -32],
      ["Undecided", -10],
      ["Hesitant", -18],
      ["Skeptical", -14],
      ["Doubtful", -28],
      ["Puzzled", -10],
      ["Perplexed", -20],
      ["Bewildered", -36],
      ["Disoriented", -44],
      ["Baffled", -24],
      ["Unclear", -14],
      ["Mixed", -4],
      ["Bittersweet", 2],
      ["Unresolved", -24],
      ["Questioning", -6],
      ["Tentative", -8],
      ["Surprised", 12],
      ["Taken aback", -20],
      ["Stunned", -14],
      ["Overthinking", -36],
      ["Out of my depth", -42],
      ["Unready", -34],
      ["Expectant", 18],
      ["On the fence", -6],
    ],
  },
  reflection: {
    impacts: ["identity", "spirituality", "family", "friends"],
    words: [
      ["Pensive", -2],
      ["Thoughtful", 4],
      ["Reflective", 4],
      ["Nostalgic", 6],
      ["Contemplative", 2],
      ["Introspective", 0],
      ["Sentimental", 14],
      ["Moved", 36],
      ["Touched", 48],
      ["Absorbed", 18],
      ["Attentive", 20],
      ["Mindful", 22],
      ["Aware", 10],
      ["Observant", 8],
      ["Open-minded", 24],
      ["Receptive", 28],
      ["Understanding", 30],
      ["Accepting", 26],
      ["Sober", -6],
      ["Serious", -2],
      ["Earnest", 10],
      ["Quietly hopeful", 20],
      ["Sympathetic", 12],
      ["Empathetic", 18],
      ["Compassionate", 42],
    ],
  },
  peace: {
    impacts: ["self-care", "sleep", "weather", "spirituality"],
    words: [
      ["Quiet", 0],
      ["Steady", 8],
      ["Calm", 10],
      ["Patient", 10],
      ["Content", 20],
      ["Grounded", 24],
      ["Comfortable", 26],
      ["Present", 26],
      ["Relaxed", 32],
      ["Relieved", 38],
      ["Peaceful", 40],
      ["Serene", 66],
      ["Free", 80],
      ["Blissful", 92],
      ["At ease", 34],
      ["Tranquil", 54],
      ["Still", 12],
      ["Settled", 24],
      ["Centered", 30],
      ["Balanced", 28],
      ["Composed", 24],
      ["Collected", 22],
      ["Secure", 38],
      ["Safe", 40],
      ["Reassured", 42],
      ["Soothed", 46],
      ["Comforted", 48],
      ["Cozy", 42],
      ["Unburdened", 52],
      ["Untroubled", 36],
      ["Carefree", 58],
      ["Lighthearted", 62],
      ["Mellow", 26],
      ["Easygoing", 32],
      ["Restful", 28],
      ["Clearheaded", 30],
      ["Unhurried", 20],
      ["At home", 44],
      ["At peace", 56],
      ["Undisturbed", 18],
      ["Unbothered", 22],
      ["Trusting", 36],
      ["Liberated", 72],
    ],
  },
  wonder: {
    impacts: ["hobbies", "school", "travel", "news"],
    words: [
      ["Curious", 14],
      ["Interested", 22],
      ["Intrigued", 30],
      ["Fascinated", 58],
      ["Amazed", 82],
      ["Awed", 86],
      ["Inquisitive", 22],
      ["Engaged", 32],
      ["Captivated", 62],
      ["Spellbound", 72],
      ["Mesmerized", 68],
      ["Enchanted", 74],
      ["Enthralled", 70],
      ["Wonderstruck", 84],
      ["Astonished", 66],
      ["Impressed", 54],
      ["Wide-eyed", 42],
      ["Awestruck", 86],
      ["Starstruck", 72],
      ["Eager to learn", 42],
      ["Surprised in a good way", 58],
      ["Exploratory", 30],
    ],
  },
  drive: {
    impacts: ["school", "work", "fitness", "tasks"],
    words: [
      ["Focused", 12],
      ["Productive", 34],
      ["Determined", 44],
      ["Motivated", 52],
      ["Passionate", 74],
      ["Unstoppable", 90],
      ["Driven", 54],
      ["Ambitious", 50],
      ["Purposeful", 56],
      ["Committed", 46],
      ["Dedicated", 48],
      ["Resolute", 50],
      ["Persistent", 44],
      ["Tenacious", 48],
      ["Ready", 38],
      ["Prepared", 34],
      ["Intent", 32],
      ["Engrossed", 36],
      ["In the zone", 58],
      ["Challenged", 24],
      ["Stretched", 16],
      ["Resourceful", 42],
      ["Proactive", 46],
      ["Diligent", 40],
      ["Competitive", 42],
      ["Fired up", 76],
      ["On a mission", 62],
      ["Resilient", 52],
      ["Gritty", 38],
      ["Bold", 60],
    ],
  },
  hope: {
    impacts: ["school", "work", "identity", "spirituality"],
    words: [
      ["Hopeful", 30],
      ["Encouraged", 36],
      ["Optimistic", 50],
      ["Positive", 44],
      ["Uplifted", 62],
      ["Buoyant", 58],
      ["Heartened", 48],
      ["Looking forward", 42],
      ["Eager", 54],
      ["Anticipating", 34],
      ["Faithful", 32],
      ["Reinvigorated", 60],
      ["Renewed", 54],
      ["Rekindled", 50],
      ["Upbeat", 58],
      ["Open to possibility", 36],
    ],
  },
  pride: {
    impacts: ["school", "work", "fitness", "tasks"],
    words: [
      ["Satisfied", 38],
      ["Capable", 40],
      ["Brave", 50],
      ["Confident", 56],
      ["Proud", 60],
      ["Accomplished", 64],
      ["Fulfilled", 76],
      ["Empowered", 80],
      ["Self-assured", 58],
      ["Self-accepting", 46],
      ["Worthy", 50],
      ["Enough", 36],
      ["Competent", 42],
      ["Effective", 40],
      ["Successful", 64],
      ["Victorious", 82],
      ["Triumphant", 88],
      ["Valued", 54],
      ["Recognized", 56],
      ["Validated", 50],
      ["Vindicated", 62],
      ["Admired", 64],
      ["Respected", 52],
      ["Honored", 66],
      ["Dignified", 44],
      ["Courageous", 58],
      ["Fearless", 72],
      ["Strong", 56],
      ["Independent", 50],
      ["Authentic", 54],
      ["Pleased with myself", 58],
      ["On top of the world", 94],
    ],
  },
  love: {
    impacts: ["friends", "family", "partner", "community"],
    words: [
      ["Included", 40],
      ["Connected", 54],
      ["Supported", 54],
      ["Appreciated", 56],
      ["Grateful", 56],
      ["Cared for", 60],
      ["Loved", 68],
      ["Loving", 72],
      ["Affectionate", 58],
      ["Warm", 46],
      ["Tenderhearted", 44],
      ["Close", 56],
      ["Accepted", 52],
      ["Understood", 54],
      ["Seen", 50],
      ["Heard", 48],
      ["Welcomed", 52],
      ["Wanted", 62],
      ["Cherished", 78],
      ["Adored", 82],
      ["Treasured", 80],
      ["Appreciative", 52],
      ["Thankful", 58],
      ["Blessed", 68],
      ["Fond", 48],
      ["Attached", 46],
      ["Devoted", 64],
      ["Loyal", 46],
      ["Companionable", 42],
      ["Sociable", 40],
      ["Friendly", 38],
      ["Generous", 48],
      ["Forgiving", 40],
      ["Reconciled", 46],
      ["In love", 88],
      ["Smitten", 78],
      ["Infatuated", 74],
      ["Romantic", 66],
      ["Flirty", 54],
      ["Playfully nervous", 28],
      ["Vulnerable but safe", 32],
    ],
  },
  joy: {
    impacts: ["friends", "hobbies", "weather", "travel"],
    words: [
      ["Silly", 44],
      ["Amused", 48],
      ["Playful", 54],
      ["Cheerful", 58],
      ["Happy", 62],
      ["Delighted", 80],
      ["Joyful", 82],
      ["Radiant", 86],
      ["Elated", 90],
      ["Overjoyed", 92],
      ["Ecstatic", 96],
      ["Euphoric", 97],
      ["Glad", 56],
      ["Pleased", 48],
      ["Merry", 64],
      ["Jolly", 66],
      ["Gleeful", 80],
      ["Jubilant", 90],
      ["Exuberant", 86],
      ["Giddy", 78],
      ["Tickled", 58],
      ["Entertained", 46],
      ["Charmed", 56],
      ["Cheered up", 52],
      ["Sunny", 62],
      ["Bright", 56],
      ["Bubbly", 70],
      ["Bouncy", 68],
      ["Over the moon", 94],
      ["Jovial", 66],
      ["Joyous", 84],
      ["Joking", 42],
      ["Goofy", 48],
      ["Mischievous", 46],
      ["Whimsical", 40],
      ["Celebratory", 78],
      ["Festive", 68],
      ["Savoring the moment", 62],
    ],
  },
  energy: {
    impacts: ["fitness", "hobbies", "travel", "friends"],
    words: [
      ["Refreshed", 34],
      ["Creative", 52],
      ["Energized", 62],
      ["Inspired", 64],
      ["Adventurous", 74],
      ["Excited", 78],
      ["Hyped", 86],
      ["Thrilled", 88],
      ["Lively", 60],
      ["Vibrant", 72],
      ["Alive", 70],
      ["Invigorated", 68],
      ["Revitalized", 66],
      ["Rejuvenated", 64],
      ["Buzzing", 78],
      ["Pumped", 82],
      ["Stoked", 84],
      ["Enthusiastic", 72],
      ["Electrified", 88],
      ["Exhilarated", 90],
      ["Raring to go", 74],
      ["Spontaneous", 58],
      ["Daring", 62],
      ["Dazzled", 76],
      ["Inventive", 50],
      ["Imaginative", 48],
      ["Expressive", 46],
      ["Stimulated", 44],
      ["Alert", 20],
      ["Awake", 14],
      ["Fresh", 38],
      ["Sparked", 56],
    ],
  },
} as const satisfies Record<
  string,
  {
    impacts: readonly ImpactId[];
    words: readonly (readonly [string, number])[];
  }
>;

export type FeelingFamily = keyof typeof feelingFamilies;
export type FeelingWord =
  (typeof feelingFamilies)[FeelingFamily]["words"][number][0];

// Familiar entry points keep a larger vocabulary from crowding the first screen.
// These are intentionally independent of the full bank and graph.
export const starterWords = [
  "Hopeless",
  "Helpless",
  "Defeated",
  "Empty",
  "Lost",
  "Discouraged",
  "Devastated",
  "Heartbroken",
  "Grieving",
  "Homesick",
  "Miserable",
  "Sad",
  "Hurt",
  "Disappointed",
  "Down",
  "Sensitive",
  "Terrified",
  "Panicked",
  "Scared",
  "Anxious",
  "Worried",
  "Nervous",
  "Uneasy",
  "Furious",
  "Disgusted",
  "Angry",
  "Frustrated",
  "Jealous",
  "Irritated",
  "Annoyed",
  "Ashamed",
  "Guilty",
  "Embarrassed",
  "Insecure",
  "Self-conscious",
  "Awkward",
  "Overwhelmed",
  "Stressed",
  "Pressured",
  "Rushed",
  "Impatient",
  "Restless",
  "Exhausted",
  "Burnt out",
  "Drained",
  "Tired",
  "Sleepy",
  "Isolated",
  "Lonely",
  "Rejected",
  "Left out",
  "Disconnected",
  "Numb",
  "Unmotivated",
  "Bored",
  "Confused",
  "Torn",
  "Distracted",
  "Uncertain",
  "Reflective",
  "Nostalgic",
  "Calm",
  "Content",
  "Grounded",
  "Comfortable",
  "Present",
  "Relaxed",
  "Relieved",
  "Peaceful",
  "Serene",
  "Free",
  "Blissful",
  "Curious",
  "Interested",
  "Fascinated",
  "Amazed",
  "Awed",
  "Focused",
  "Productive",
  "Determined",
  "Motivated",
  "Passionate",
  "Unstoppable",
  "Hopeful",
  "Optimistic",
  "Satisfied",
  "Capable",
  "Brave",
  "Confident",
  "Proud",
  "Accomplished",
  "Fulfilled",
  "Empowered",
  "Connected",
  "Supported",
  "Appreciated",
  "Grateful",
  "Cared for",
  "Loved",
  "Silly",
  "Amused",
  "Playful",
  "Cheerful",
  "Happy",
  "Delighted",
  "Joyful",
  "Elated",
  "Overjoyed",
  "Ecstatic",
  "Euphoric",
  "Refreshed",
  "Creative",
  "Energized",
  "Inspired",
  "Adventurous",
  "Excited",
  "Hyped",
  "Thrilled",
  "Okay",
  "Mixed",
  "Bittersweet",
  "Safe",
  "Rested",
  "In love",
  "Triumphant",
  "On top of the world",
] as const satisfies readonly FeelingWord[];

// Each neighborhood creates links in BOTH directions. A word may appear in as
// many neighborhoods as fit. Small, specific groups beat linking whole families.
export const feelingNeighborhoods = [
  [
    "Devastated",
    "Heartbroken",
    "Crushed",
    "Shattered",
    "Gutted",
    "Brokenhearted",
    "Inconsolable",
  ],
  [
    "Devastated",
    "Hopeless",
    "Despairing",
    "Desolate",
    "Anguished",
    "Miserable",
  ],
  [
    "Grieving",
    "Bereaved",
    "Bereft",
    "Mournful",
    "Sorrowful",
    "Heavyhearted",
    "Heartsick",
  ],
  ["Heartbroken", "Hurt", "Rejected", "Abandoned", "Betrayed", "Unwanted"],
  [
    "Missing someone",
    "Homesick",
    "Lonely",
    "Longing",
    "Yearning",
    "Nostalgic",
    "Wistful",
  ],
  [
    "Lovesick",
    "Longing",
    "Yearning",
    "Heartsick",
    "Heartbroken",
    "Missing someone",
  ],
  ["Empty", "Hollow", "Numb", "Blank", "Emotionless", "Detached from myself"],
  [
    "Lost",
    "Adrift",
    "Unmoored",
    "Directionless",
    "Aimless",
    "Disoriented",
    "Displaced",
  ],
  ["Hopeless", "Despondent", "Bleak", "Defeated", "Despairing", "Resigned"],
  [
    "Defeated",
    "Demoralized",
    "Beaten down",
    "Downtrodden",
    "Discouraged",
    "Disheartened",
  ],
  [
    "Disappointed",
    "Let down",
    "Deflated",
    "Crestfallen",
    "Dejected",
    "Dismayed",
  ],
  [
    "Helpless",
    "Powerless",
    "Trapped",
    "Cornered",
    "Out of control",
    "Suffocated",
  ],
  [
    "Stuck",
    "Stagnant",
    "Unfulfilled",
    "Discouraged",
    "Directionless",
    "Unmotivated",
  ],
  ["Sad", "Down", "Blue", "Low", "Unhappy", "Saddened", "Downhearted"],
  ["Sad", "Tearful", "Weepy", "Sorrowful", "Heavyhearted", "Aching"],
  ["Gloomy", "Glum", "Somber", "Melancholy", "Doleful", "Forlorn", "Sullen"],
  ["Sensitive", "Vulnerable", "Tender", "Raw", "Fragile", "Hurt", "Exposed"],
  ["Regretful", "Remorseful", "Guilty", "Contrite", "Disappointed in myself"],
  [
    "Terrified",
    "Petrified",
    "Horrified",
    "Panicked",
    "Freaked out",
    "Frightened",
  ],
  ["Scared", "Afraid", "Frightened", "Threatened", "Unsafe", "Intimidated"],
  ["Worried", "Concerned", "Anxious", "Fretful", "Overthinking", "Troubled"],
  ["Anxious", "Stressed", "Tense", "On edge", "Wound up", "Agitated"],
  ["Nervous", "Jittery", "Shaky", "Fidgety", "Antsy", "Restless", "Edgy"],
  ["Uneasy", "Unsettled", "Apprehensive", "Wary", "Doubtful", "Hesitant"],
  [
    "Dreading",
    "Daunted",
    "Apprehensive",
    "Intimidated",
    "Unprepared",
    "Unready",
  ],
  [
    "Startled",
    "Spooked",
    "Alarmed",
    "Rattled",
    "In shock",
    "Taken aback",
    "Stunned",
  ],
  ["Guarded", "Suspicious", "Distrustful", "Defensive", "Wary", "Closed off"],
  ["Cautious", "Hesitant", "Tentative", "Skeptical", "Unsure", "Questioning"],
  ["Furious", "Livid", "Enraged", "Fuming", "Seething", "Irate", "Mad"],
  [
    "Angry",
    "Mad",
    "Frustrated",
    "Provoked",
    "Aggravated",
    "Exasperated",
    "Fed up",
  ],
  ["Outraged", "Indignant", "Wronged", "Offended", "Insulted", "Cheated"],
  ["Bitter", "Resentful", "Betrayed", "Spiteful", "Vengeful", "Hostile"],
  [
    "Annoyed",
    "Irritated",
    "Irritable",
    "Cranky",
    "Grumpy",
    "Sour",
    "Impatient",
  ],
  [
    "Disgusted",
    "Appalled",
    "Repulsed",
    "Revolted",
    "Horrified",
    "Contemptuous",
  ],
  ["Jealous", "Envious", "Possessive", "Insecure", "Threatened", "Resentful"],
  ["Embarrassed", "Mortified", "Humiliated", "Ashamed", "Exposed", "Judged"],
  [
    "Awkward",
    "Self-conscious",
    "Sheepish",
    "Bashful",
    "Shy",
    "Flustered",
    "Foolish",
  ],
  [
    "Insecure",
    "Self-doubting",
    "Uncertain of myself",
    "Inadequate",
    "Self-critical",
    "Inferior",
  ],
  ["Unworthy", "Unlovable", "Unwanted", "Small", "Inadequate", "Unattractive"],
  [
    "Out of place",
    "Uncomfortable",
    "Unwelcome",
    "Excluded",
    "Awkward",
    "Alienated",
  ],
  [
    "Overwhelmed",
    "Overloaded",
    "Swamped",
    "Overburdened",
    "Overextended",
    "Pulled in every direction",
  ],
  [
    "Stressed",
    "Under pressure",
    "Pressured",
    "Stretched thin",
    "Overworked",
    "Weighed down",
  ],
  ["Rushed", "Harried", "Hassled", "Frantic", "Frazzled", "On the spot"],
  [
    "Overstimulated",
    "Overwhelmed",
    "Agitated",
    "Frazzled",
    "Socially drained",
    "Wound up",
  ],
  [
    "Burnt out",
    "Mentally exhausted",
    "Emotionally drained",
    "Depleted",
    "Overworked",
    "Fried",
  ],
  [
    "Exhausted",
    "Worn out",
    "Wiped out",
    "Spent",
    "Drained",
    "Sapped",
    "Fatigued",
  ],
  [
    "Tired",
    "Weary",
    "Sluggish",
    "Low-energy",
    "Lethargic",
    "Listless",
    "Heavy",
  ],
  ["Sleepy", "Drowsy", "Groggy", "Foggy", "Spaced out", "Unfocused"],
  ["Sick", "Unwell", "Under the weather", "Run-down", "Achy", "Sore"],
  [
    "Rested",
    "Well-rested",
    "Refreshed",
    "Recharged",
    "Restored",
    "Rejuvenated",
  ],
  ["Lonely", "Alone", "Isolated", "Disconnected", "Forlorn", "Estranged"],
  [
    "Ignored",
    "Invisible",
    "Unseen",
    "Unheard",
    "Overlooked",
    "Disregarded",
    "Neglected",
  ],
  ["Rejected", "Left out", "Excluded", "Shut out", "Unwelcome", "Abandoned"],
  [
    "Misunderstood",
    "Dismissed",
    "Invalidated",
    "Unheard",
    "Unsupported",
    "Unappreciated",
  ],
  [
    "Withdrawn",
    "Distant",
    "Detached",
    "Closed off",
    "Disconnected",
    "Out of sync",
  ],
  ["Flat", "Blah", "Meh", "Bored", "Dull", "Unenthusiastic", "Uninterested"],
  ["Apathetic", "Indifferent", "Unmoved", "Disengaged", "Checked out", "Numb"],
  [
    "Unmotivated",
    "Uninspired",
    "Aimless",
    "Stagnant",
    "Listless",
    "Unfulfilled",
  ],
  ["Neutral", "Okay", "Fine", "So-so", "Steady", "Quiet"],
  [
    "Distracted",
    "Preoccupied",
    "Unfocused",
    "Absent-minded",
    "Foggy",
    "Spaced out",
  ],
  [
    "Confused",
    "Puzzled",
    "Perplexed",
    "Bewildered",
    "Baffled",
    "Unclear",
    "Dazed",
  ],
  [
    "Torn",
    "Conflicted",
    "Ambivalent",
    "Mixed",
    "Undecided",
    "On the fence",
    "Unresolved",
  ],
  ["Bittersweet", "Nostalgic", "Wistful", "Sentimental", "Moved", "Tender"],
  ["Surprised", "Astonished", "Taken aback", "Stunned", "Amazed", "Wide-eyed"],
  [
    "Pensive",
    "Thoughtful",
    "Reflective",
    "Contemplative",
    "Introspective",
    "Serious",
    "Sober",
  ],
  [
    "Present",
    "Mindful",
    "Aware",
    "Attentive",
    "Observant",
    "Grounded",
    "Centered",
  ],
  [
    "Open-minded",
    "Receptive",
    "Understanding",
    "Accepting",
    "Empathetic",
    "Compassionate",
    "Sympathetic",
  ],
  [
    "Calm",
    "At ease",
    "Relaxed",
    "Mellow",
    "Untroubled",
    "Unhurried",
    "Easygoing",
  ],
  [
    "Peaceful",
    "Tranquil",
    "Serene",
    "At peace",
    "Still",
    "Restful",
    "Undisturbed",
  ],
  [
    "Steady",
    "Balanced",
    "Composed",
    "Collected",
    "Settled",
    "Clearheaded",
    "Grounded",
  ],
  [
    "Safe",
    "Secure",
    "Reassured",
    "Comforted",
    "Soothed",
    "Supported",
    "Trusting",
  ],
  ["Comfortable", "Cozy", "At home", "Content", "Warm", "Cared for"],
  [
    "Relieved",
    "Unburdened",
    "Free",
    "Liberated",
    "Carefree",
    "Lighthearted",
    "Unbothered",
  ],
  [
    "Curious",
    "Interested",
    "Inquisitive",
    "Intrigued",
    "Exploratory",
    "Eager to learn",
  ],
  [
    "Fascinated",
    "Captivated",
    "Spellbound",
    "Mesmerized",
    "Enthralled",
    "Absorbed",
    "Engrossed",
  ],
  [
    "Awed",
    "Awestruck",
    "Wonderstruck",
    "Amazed",
    "Astonished",
    "Impressed",
    "Dazzled",
  ],
  [
    "Enchanted",
    "Charmed",
    "Starstruck",
    "Delighted",
    "Surprised in a good way",
  ],
  [
    "Focused",
    "Engaged",
    "Absorbed",
    "Attentive",
    "In the zone",
    "Intent",
    "Productive",
  ],
  [
    "Determined",
    "Resolute",
    "Persistent",
    "Tenacious",
    "Committed",
    "Dedicated",
    "Gritty",
  ],
  [
    "Motivated",
    "Driven",
    "Ambitious",
    "Purposeful",
    "Proactive",
    "On a mission",
    "Passionate",
  ],
  [
    "Ready",
    "Prepared",
    "Capable",
    "Competent",
    "Resourceful",
    "Effective",
    "Diligent",
  ],
  [
    "Challenged",
    "Stretched",
    "Competitive",
    "Determined",
    "Resilient",
    "Brave",
  ],
  [
    "Hopeful",
    "Optimistic",
    "Positive",
    "Encouraged",
    "Heartened",
    "Quietly hopeful",
    "Open to possibility",
  ],
  [
    "Eager",
    "Looking forward",
    "Anticipating",
    "Expectant",
    "Excited",
    "Enthusiastic",
  ],
  [
    "Renewed",
    "Rekindled",
    "Reinvigorated",
    "Uplifted",
    "Buoyant",
    "Upbeat",
    "Inspired",
  ],
  ["Faithful", "Hopeful", "Trusting", "Grateful", "Blessed"],
  [
    "Confident",
    "Self-assured",
    "Capable",
    "Strong",
    "Empowered",
    "Independent",
  ],
  ["Self-accepting", "Worthy", "Enough", "Authentic", "Secure", "Accepted"],
  ["Brave", "Courageous", "Fearless", "Bold", "Daring", "Resilient"],
  [
    "Proud",
    "Accomplished",
    "Successful",
    "Pleased with myself",
    "Satisfied",
    "Fulfilled",
  ],
  [
    "Victorious",
    "Triumphant",
    "Unstoppable",
    "On top of the world",
    "Elated",
    "Jubilant",
  ],
  [
    "Valued",
    "Recognized",
    "Validated",
    "Appreciated",
    "Respected",
    "Honored",
    "Admired",
  ],
  ["Vindicated", "Validated", "Heard", "Respected", "Dignified"],
  ["Connected", "Close", "Included", "Accepted", "Welcomed", "Companionable"],
  [
    "Supported",
    "Understood",
    "Seen",
    "Heard",
    "Cared for",
    "Vulnerable but safe",
  ],
  ["Loved", "Cherished", "Adored", "Treasured", "Wanted", "Appreciated"],
  [
    "Loving",
    "Affectionate",
    "Warm",
    "Tenderhearted",
    "Fond",
    "Compassionate",
    "Generous",
  ],
  [
    "In love",
    "Smitten",
    "Infatuated",
    "Romantic",
    "Flirty",
    "Playfully nervous",
  ],
  ["Devoted", "Attached", "Loyal", "Close", "Loving", "Trusting"],
  ["Grateful", "Thankful", "Appreciative", "Blessed", "Touched", "Moved"],
  [
    "Forgiving",
    "Reconciled",
    "Accepting",
    "Understanding",
    "Relieved",
    "At peace",
  ],
  ["Friendly", "Sociable", "Companionable", "Playful", "Warm", "Welcomed"],
  ["Happy", "Glad", "Cheerful", "Sunny", "Bright", "Upbeat", "Cheered up"],
  [
    "Joyful",
    "Joyous",
    "Merry",
    "Jolly",
    "Jovial",
    "Radiant",
    "Celebratory",
    "Festive",
  ],
  ["Delighted", "Pleased", "Amused", "Tickled", "Entertained", "Charmed"],
  ["Silly", "Goofy", "Playful", "Joking", "Mischievous", "Whimsical"],
  ["Giddy", "Bubbly", "Bouncy", "Gleeful", "Exuberant", "Lively"],
  [
    "Overjoyed",
    "Ecstatic",
    "Euphoric",
    "Over the moon",
    "Elated",
    "Blissful",
    "Jubilant",
  ],
  [
    "Content",
    "Satisfied",
    "Fulfilled",
    "Pleased",
    "Savoring the moment",
    "Present",
  ],
  [
    "Energized",
    "Invigorated",
    "Revitalized",
    "Vibrant",
    "Alive",
    "Refreshed",
    "Recharged",
  ],
  [
    "Excited",
    "Hyped",
    "Pumped",
    "Stoked",
    "Buzzing",
    "Fired up",
    "Raring to go",
  ],
  [
    "Thrilled",
    "Exhilarated",
    "Electrified",
    "Ecstatic",
    "Enthusiastic",
    "Passionate",
  ],
  ["Adventurous", "Spontaneous", "Daring", "Bold", "Free", "Exploratory"],
  ["Creative", "Inventive", "Imaginative", "Inspired", "Expressive", "Sparked"],
  ["Stimulated", "Alert", "Awake", "Fresh", "Engaged", "Interested"],
] as const satisfies readonly (readonly FeelingWord[])[];

// Strong bridges connect specific meanings across neighborhoods. The first word
// connects to each subsequent word, in both directions (not a parent/child tree).
export const feelingBridges = [
  [
    "Devastated",
    "Heartbroken",
    "Grieving",
    "Hopeless",
    "Crushed",
    "Shattered",
    "Miserable",
    "Despairing",
    "Hurt",
    "Sad",
    "Disappointed",
    "Defeated",
    "Overwhelmed",
  ],
  ["Sad", "Down", "Sorrowful", "Tearful", "Heavyhearted"],
  ["Anxious", "Worried", "Stressed", "On edge", "Apprehensive", "Overthinking"],
  [
    "Overwhelmed",
    "Overloaded",
    "Swamped",
    "Overstimulated",
    "Stressed",
    "Helpless",
    "Emotionally drained",
  ],
  [
    "Burnt out",
    "Exhausted",
    "Depleted",
    "Unmotivated",
    "Mentally exhausted",
    "Emotionally drained",
  ],
  [
    "Lonely",
    "Disconnected",
    "Missing someone",
    "Isolated",
    "Left out",
    "Unseen",
  ],
  ["Angry", "Frustrated", "Furious", "Resentful", "Wronged", "Betrayed"],
  [
    "Insecure",
    "Self-conscious",
    "Self-doubting",
    "Vulnerable",
    "Jealous",
    "Uncertain of myself",
  ],
  ["Bittersweet", "Nostalgic", "Wistful", "Mixed", "Sentimental", "Moved"],
  ["Calm", "Relaxed", "Grounded", "At ease", "Peaceful", "Safe"],
  ["Happy", "Joyful", "Content", "Cheerful", "Delighted", "Grateful"],
  [
    "Proud",
    "Accomplished",
    "Fulfilled",
    "Confident",
    "Recognized",
    "Triumphant",
  ],
  ["Excited", "Eager", "Enthusiastic", "Thrilled", "Inspired", "Hyped"],
  ["Loved", "Connected", "Cherished", "Supported", "Accepted", "Cared for"],
  ["Grateful", "Thankful", "Appreciative", "Touched", "Loved", "Fulfilled"],
  ["Hopeful", "Optimistic", "Encouraged", "Uplifted", "Quietly hopeful"],
] as const satisfies readonly (readonly FeelingWord[])[];

// Search understands common spellings, nouns, and everyday phrases without
// saving several spellings of the same feeling as separate choices.
export const feelingAliases = {
  "Burnt out": ["burnout", "burned out", "burn out"],
  Devastated: ["devastation", "devastating"],
  Heartbroken: ["heartbreak", "heart broken", "broken heart"],
  Grieving: ["grief", "mourning", "grief stricken"],
  Sad: ["sadness", "sadness inside"],
  Anxious: ["anxiety", "anxiousness"],
  Angry: ["anger", "pissed", "pissed off"],
  Scared: ["fear", "fearful"],
  Panicked: ["panic", "panicky"],
  Nervous: ["nerves", "nervousness"],
  Stressed: ["stress", "stressing"],
  Overwhelmed: ["overwhelm", "too much", "overwhelming"],
  Overstimulated: ["sensory overload", "overstimulation"],
  Lonely: ["loneliness", "lonesome"],
  Jealous: ["jealousy"],
  Envious: ["envy"],
  Ashamed: ["shame"],
  Guilty: ["guilt"],
  Embarrassed: ["embarrassment"],
  Regretful: ["regret"],
  Bored: ["boredom"],
  Tired: ["tiredness", "fatigue"],
  Exhausted: ["exhaustion", "exhausting"],
  Unmotivated: ["no motivation", "not motivated"],
  Uninspired: ["no inspiration"],
  Restless: ["restlessness", "cant sit still"],
  "Fed up": ["over it", "had enough", "done with it"],
  "Left out": ["fomo", "leftout"],
  "Self-conscious": ["self conscious", "selfconscious"],
  "Self-doubting": ["self doubt", "imposter syndrome", "impostor syndrome"],
  Okay: ["ok", "alright", "all right"],
  "So-so": ["so so", "soso"],
  Bittersweet: ["bitter sweet", "happy and sad", "sad and happy"],
  Mixed: ["mixed feelings", "mixed emotions"],
  Nostalgic: ["nostalgia"],
  Confused: ["confusion"],
  Calm: ["calmness"],
  Peaceful: ["peace", "peacefulness"],
  Relieved: ["relief"],
  Happy: ["happiness"],
  Joyful: ["joy"],
  Grateful: ["gratitude", "thankfulness"],
  Proud: ["pride"],
  Confident: ["confidence"],
  Hopeful: ["hope"],
  Excited: ["excitement", "exciting"],
  Energized: ["energised", "energy", "energetic"],
  Fulfilled: ["fulfilment", "fulfillment"],
  Loved: ["love", "feeling loved"],
  "In love": ["inlove", "falling in love"],
  "Cared for": ["cared about", "caredfor"],
  "Missing someone": ["miss someone", "missing home"],
} as const satisfies Partial<Record<FeelingWord, readonly string[]>>;
