import type { ImpactId } from "@/lib/mood";

// One canonical word per feeling. Keep the bank to real emotion words: no
// phrases, traits, or physical symptoms, and no near-duplicates of a word that
// is already here. The family only supplies default impacts; related-word
// discovery uses overlapping groups below, not a single parent. Valence is an
// editorial browsing hint, never a limit on what someone can select.
export const feelingFamilies = {
  despair: {
    impacts: ["school", "health", "identity", "work"],
    words: [
      ["Hopeless", -95],
      ["Helpless", -85],
      ["Defeated", -82],
      ["Powerless", -80],
      ["Empty", -70],
      ["Lost", -60],
      ["Discouraged", -52],
      ["Despairing", -94],
      ["Crushed", -90],
      ["Shattered", -94],
      ["Demoralized", -76],
      ["Disheartened", -64],
      ["Trapped", -74],
      ["Stuck", -46],
      ["Deflated", -48],
      ["Resigned", -44],
      ["Pessimistic", -42],
      ["Abandoned", -82],
    ],
  },
  grief: {
    impacts: ["family", "friends", "partner", "dating"],
    words: [
      ["Devastated", -96],
      ["Heartbroken", -92],
      ["Grieving", -88],
      ["Homesick", -38],
      ["Sorrowful", -74],
      ["Anguished", -90],
      ["Longing", -32],
      ["Lovesick", -44],
      ["Hollow", -68],
      ["Shocked", -60],
      ["Dismayed", -64],
    ],
  },
  sadness: {
    impacts: ["friends", "family", "partner", "school"],
    words: [
      ["Miserable", -90],
      ["Sad", -66],
      ["Hurt", -62],
      ["Disappointed", -50],
      ["Down", -46],
      ["Gloomy", -40],
      ["Sensitive", -24],
      ["Wistful", -10],
      ["Unhappy", -58],
      ["Upset", -60],
      ["Melancholy", -44],
      ["Blue", -40],
      ["Tearful", -56],
      ["Dejected", -60],
      ["Somber", -36],
      ["Tender", -8],
      ["Vulnerable", -30],
      ["Fragile", -48],
      ["Regretful", -52],
    ],
  },
  fear: {
    impacts: ["school", "health", "money", "news"],
    words: [
      ["Terrified", -92],
      ["Panicked", -86],
      ["Scared", -68],
      ["Anxious", -60],
      ["Worried", -48],
      ["Nervous", -35],
      ["Uneasy", -28],
      ["Afraid", -66],
      ["Apprehensive", -44],
      ["Dreading", -66],
      ["Horrified", -92],
      ["Threatened", -78],
      ["Unsafe", -76],
      ["On edge", -52],
      ["Jittery", -38],
      ["Tense", -44],
      ["Unsettled", -38],
      ["Rattled", -54],
      ["Startled", -30],
      ["Wary", -26],
      ["Guarded", -24],
      ["Cautious", -8],
      ["Suspicious", -36],
      ["Intimidated", -54],
    ],
  },
  anger: {
    impacts: ["friends", "family", "school", "work"],
    words: [
      ["Furious", -88],
      ["Disgusted", -72],
      ["Angry", -68],
      ["Resentful", -58],
      ["Frustrated", -55],
      ["Jealous", -50],
      ["Irritated", -38],
      ["Annoyed", -30],
      ["Mad", -62],
      ["Outraged", -84],
      ["Indignant", -60],
      ["Exasperated", -52],
      ["Bitter", -62],
      ["Hostile", -70],
      ["Vengeful", -78],
      ["Offended", -50],
      ["Disrespected", -62],
      ["Betrayed", -82],
      ["Fed up", -54],
      ["Grumpy", -28],
      ["Defensive", -36],
      ["Appalled", -78],
    ],
  },
  shame: {
    impacts: ["identity", "friends", "school", "dating"],
    words: [
      ["Ashamed", -84],
      ["Guilty", -60],
      ["Embarrassed", -50],
      ["Insecure", -48],
      ["Self-conscious", -34],
      ["Awkward", -26],
      ["Humiliated", -86],
      ["Mortified", -80],
      ["Remorseful", -68],
      ["Inadequate", -60],
      ["Inferior", -58],
      ["Unworthy", -72],
      ["Exposed", -48],
      ["Judged", -54],
      ["Foolish", -40],
      ["Sheepish", -28],
      ["Flustered", -30],
      ["Shy", -8],
      ["Uncomfortable", -34],
      ["Unlovable", -76],
      ["Unwanted", -72],
    ],
  },
  stress: {
    impacts: ["school", "work", "tasks", "money"],
    words: [
      ["Overwhelmed", -76],
      ["Stressed", -58],
      ["Pressured", -42],
      ["Rushed", -32],
      ["Impatient", -26],
      ["Restless", -24],
      ["Frazzled", -58],
      ["Frantic", -72],
      ["Overstimulated", -60],
      ["Antsy", -22],
      ["Unprepared", -44],
      ["Suffocated", -76],
      ["Burdened", -58],
      ["Preoccupied", -20],
      ["Agitated", -54],
      ["Troubled", -48],
    ],
  },
  tiredness: {
    impacts: ["sleep", "health", "school", "fitness"],
    words: [
      ["Exhausted", -72],
      ["Burnt out", -68],
      ["Drained", -56],
      ["Tired", -32],
      ["Sluggish", -24],
      ["Sleepy", -10],
      ["Depleted", -62],
      ["Weary", -48],
      ["Groggy", -28],
      ["Foggy", -30],
      ["Lethargic", -38],
      ["Overworked", -60],
      ["Unwell", -52],
      ["Rested", 32],
      ["Recharged", 50],
    ],
  },
  disconnection: {
    impacts: ["friends", "family", "community", "dating"],
    words: [
      ["Isolated", -80],
      ["Lonely", -74],
      ["Rejected", -70],
      ["Left out", -52],
      ["Withdrawn", -40],
      ["Disconnected", -36],
      ["Detached", -14],
      ["Invisible", -66],
      ["Ignored", -58],
      ["Misunderstood", -52],
      ["Alienated", -68],
      ["Unwelcome", -58],
      ["Unsupported", -64],
      ["Unappreciated", -54],
      ["Neglected", -72],
      ["Distant", -30],
      ["Dismissed", -56],
    ],
  },
  flatness: {
    impacts: ["tasks", "phone", "hobbies", "school"],
    words: [
      ["Numb", -64],
      ["Apathetic", -40],
      ["Unmotivated", -30],
      ["Bored", -22],
      ["Indifferent", -6],
      ["Flat", -28],
      ["Meh", -8],
      ["Uninspired", -28],
      ["Unfulfilled", -48],
      ["Dissatisfied", -38],
      ["Aimless", -32],
      ["Dazed", -26],
      ["Okay", 4],
    ],
  },
  uncertainty: {
    impacts: ["school", "identity", "dating", "work"],
    words: [
      ["Confused", -28],
      ["Torn", -22],
      ["Distracted", -18],
      ["Uncertain", -16],
      ["Ambivalent", -6],
      ["Conflicted", -32],
      ["Hesitant", -18],
      ["Skeptical", -14],
      ["Doubtful", -28],
      ["Puzzled", -10],
      ["Disoriented", -44],
      ["Mixed", -4],
      ["Bittersweet", 2],
      ["Surprised", 12],
      ["Stunned", -14],
    ],
  },
  reflection: {
    impacts: ["identity", "spirituality", "family", "friends"],
    words: [
      ["Pensive", -2],
      ["Thoughtful", 4],
      ["Reflective", 4],
      ["Nostalgic", 6],
      ["Introspective", 0],
      ["Sentimental", 14],
      ["Moved", 36],
      ["Touched", 48],
      ["Accepting", 26],
      ["Earnest", 10],
      ["Sympathetic", 12],
      ["Compassionate", 42],
    ],
  },
  peace: {
    impacts: ["self-care", "sleep", "weather", "spirituality"],
    words: [
      ["Steady", 8],
      ["Calm", 10],
      ["Patient", 10],
      ["Content", 20],
      ["Grounded", 24],
      ["Comfortable", 26],
      ["Present", 26],
      ["Relaxed", 32],
      ["Relieved", 38],
      ["Peaceful", 40],
      ["Serene", 66],
      ["Free", 80],
      ["Blissful", 92],
      ["Balanced", 28],
      ["Secure", 38],
      ["Safe", 40],
      ["Reassured", 42],
      ["Comforted", 48],
      ["Cozy", 42],
      ["Carefree", 58],
      ["Lighthearted", 62],
      ["Mellow", 26],
      ["Unbothered", 22],
      ["Trusting", 36],
    ],
  },
  wonder: {
    impacts: ["hobbies", "school", "travel", "news"],
    words: [
      ["Curious", 14],
      ["Interested", 22],
      ["Intrigued", 30],
      ["Fascinated", 58],
      ["Amazed", 82],
      ["Awed", 86],
      ["Engaged", 32],
      ["Captivated", 62],
      ["Enchanted", 74],
      ["Astonished", 66],
      ["Impressed", 54],
    ],
  },
  drive: {
    impacts: ["school", "work", "fitness", "tasks"],
    words: [
      ["Focused", 12],
      ["Productive", 34],
      ["Determined", 44],
      ["Motivated", 52],
      ["Passionate", 74],
      ["Unstoppable", 90],
      ["Ambitious", 50],
      ["Purposeful", 56],
      ["Committed", 46],
      ["Ready", 38],
      ["Prepared", 34],
      ["Challenged", 24],
      ["Competitive", 42],
      ["Resilient", 52],
      ["Bold", 60],
    ],
  },
  hope: {
    impacts: ["school", "work", "identity", "spirituality"],
    words: [
      ["Hopeful", 30],
      ["Encouraged", 36],
      ["Optimistic", 50],
      ["Positive", 44],
      ["Uplifted", 62],
      ["Eager", 54],
      ["Faithful", 32],
      ["Renewed", 54],
      ["Upbeat", 58],
    ],
  },
  pride: {
    impacts: ["school", "work", "fitness", "tasks"],
    words: [
      ["Satisfied", 38],
      ["Capable", 40],
      ["Brave", 50],
      ["Confident", 56],
      ["Proud", 60],
      ["Accomplished", 64],
      ["Fulfilled", 76],
      ["Empowered", 80],
      ["Worthy", 50],
      ["Successful", 64],
      ["Triumphant", 88],
      ["Valued", 54],
      ["Recognized", 56],
      ["Validated", 50],
      ["Respected", 52],
      ["Fearless", 72],
      ["Strong", 56],
      ["Independent", 50],
    ],
  },
  love: {
    impacts: ["friends", "family", "partner", "community"],
    words: [
      ["Included", 40],
      ["Connected", 54],
      ["Supported", 54],
      ["Appreciated", 56],
      ["Grateful", 56],
      ["Cared for", 60],
      ["Loved", 68],
      ["Loving", 72],
      ["Affectionate", 58],
      ["Warm", 46],
      ["Close", 56],
      ["Accepted", 52],
      ["Understood", 54],
      ["Seen", 50],
      ["Wanted", 62],
      ["Cherished", 78],
      ["Adored", 82],
      ["Blessed", 68],
      ["Attached", 46],
      ["Sociable", 40],
      ["Forgiving", 40],
      ["In love", 88],
      ["Smitten", 78],
      ["Romantic", 66],
      ["Flirty", 54],
    ],
  },
  joy: {
    impacts: ["friends", "hobbies", "weather", "travel"],
    words: [
      ["Silly", 44],
      ["Amused", 48],
      ["Playful", 54],
      ["Cheerful", 58],
      ["Happy", 62],
      ["Delighted", 80],
      ["Joyful", 82],
      ["Elated", 90],
      ["Overjoyed", 92],
      ["Ecstatic", 96],
      ["Euphoric", 97],
      ["Glad", 56],
      ["Pleased", 48],
      ["Giddy", 78],
      ["Bubbly", 70],
      ["Goofy", 48],
    ],
  },
  energy: {
    impacts: ["fitness", "hobbies", "travel", "friends"],
    words: [
      ["Refreshed", 34],
      ["Creative", 52],
      ["Energized", 62],
      ["Inspired", 64],
      ["Adventurous", 74],
      ["Excited", 78],
      ["Hyped", 86],
      ["Thrilled", 88],
      ["Alive", 70],
      ["Pumped", 82],
      ["Stoked", 84],
      ["Enthusiastic", 72],
      ["Exhilarated", 90],
      ["Spontaneous", 58],
      ["Alert", 20],
    ],
  },
} as const satisfies Record<
  string,
  {
    impacts: readonly ImpactId[];
    words: readonly (readonly [string, number])[];
  }
>;

export type FeelingFamily = keyof typeof feelingFamilies;
export type FeelingWord =
  (typeof feelingFamilies)[FeelingFamily]["words"][number][0];

// Familiar entry points keep the bank from crowding the first screen.
// These are intentionally independent of the full bank and graph.
export const starterWords = [
  "Hopeless",
  "Helpless",
  "Defeated",
  "Empty",
  "Lost",
  "Discouraged",
  "Devastated",
  "Heartbroken",
  "Grieving",
  "Homesick",
  "Miserable",
  "Sad",
  "Hurt",
  "Disappointed",
  "Down",
  "Sensitive",
  "Terrified",
  "Panicked",
  "Scared",
  "Anxious",
  "Worried",
  "Nervous",
  "Uneasy",
  "Furious",
  "Disgusted",
  "Angry",
  "Frustrated",
  "Jealous",
  "Irritated",
  "Annoyed",
  "Ashamed",
  "Guilty",
  "Embarrassed",
  "Insecure",
  "Self-conscious",
  "Awkward",
  "Overwhelmed",
  "Stressed",
  "Pressured",
  "Rushed",
  "Impatient",
  "Restless",
  "Exhausted",
  "Burnt out",
  "Drained",
  "Tired",
  "Sleepy",
  "Isolated",
  "Lonely",
  "Rejected",
  "Left out",
  "Disconnected",
  "Numb",
  "Unmotivated",
  "Bored",
  "Confused",
  "Torn",
  "Distracted",
  "Uncertain",
  "Reflective",
  "Nostalgic",
  "Calm",
  "Content",
  "Grounded",
  "Comfortable",
  "Present",
  "Relaxed",
  "Relieved",
  "Peaceful",
  "Serene",
  "Free",
  "Blissful",
  "Curious",
  "Interested",
  "Fascinated",
  "Amazed",
  "Awed",
  "Focused",
  "Productive",
  "Determined",
  "Motivated",
  "Passionate",
  "Unstoppable",
  "Hopeful",
  "Optimistic",
  "Eager",
  "Satisfied",
  "Capable",
  "Brave",
  "Confident",
  "Proud",
  "Accomplished",
  "Fulfilled",
  "Empowered",
  "Connected",
  "Supported",
  "Appreciated",
  "Grateful",
  "Cared for",
  "Loved",
  "Silly",
  "Amused",
  "Playful",
  "Cheerful",
  "Happy",
  "Delighted",
  "Joyful",
  "Elated",
  "Overjoyed",
  "Ecstatic",
  "Euphoric",
  "Refreshed",
  "Creative",
  "Energized",
  "Inspired",
  "Adventurous",
  "Excited",
  "Hyped",
  "Thrilled",
  "Okay",
  "Mixed",
  "Bittersweet",
  "Safe",
  "Rested",
  "In love",
  "Triumphant",
] as const satisfies readonly FeelingWord[];

// Each neighborhood creates links in BOTH directions. A word may appear in as
// many neighborhoods as fit. Small, specific groups beat linking whole families.
export const feelingNeighborhoods = [
  ["Devastated", "Heartbroken", "Crushed", "Shattered", "Anguished"],
  ["Devastated", "Hopeless", "Despairing", "Miserable", "Anguished"],
  ["Grieving", "Sorrowful", "Tearful", "Hollow", "Empty"],
  ["Heartbroken", "Hurt", "Rejected", "Abandoned", "Betrayed", "Unwanted"],
  ["Homesick", "Lonely", "Longing", "Nostalgic", "Wistful"],
  ["Lovesick", "Longing", "Heartbroken", "Wistful"],
  ["Empty", "Hollow", "Numb", "Detached", "Flat"],
  ["Lost", "Aimless", "Disoriented", "Confused", "Stuck"],
  ["Hopeless", "Defeated", "Despairing", "Resigned", "Pessimistic"],
  ["Defeated", "Demoralized", "Discouraged", "Disheartened", "Deflated"],
  ["Disappointed", "Deflated", "Dejected", "Dismayed", "Disheartened"],
  ["Helpless", "Powerless", "Trapped", "Stuck", "Suffocated"],
  ["Stuck", "Unfulfilled", "Unmotivated", "Aimless", "Dissatisfied"],
  ["Sad", "Down", "Blue", "Unhappy", "Upset", "Miserable"],
  ["Sad", "Tearful", "Sorrowful", "Hurt", "Melancholy"],
  ["Gloomy", "Somber", "Melancholy", "Blue", "Pessimistic"],
  ["Sensitive", "Vulnerable", "Tender", "Fragile", "Exposed", "Hurt"],
  ["Regretful", "Remorseful", "Guilty", "Ashamed"],
  ["Terrified", "Panicked", "Horrified", "Scared", "Afraid"],
  ["Scared", "Afraid", "Threatened", "Unsafe", "Intimidated"],
  ["Worried", "Anxious", "Troubled", "Preoccupied", "Uneasy"],
  ["Anxious", "Stressed", "Tense", "On edge", "Agitated"],
  ["Nervous", "Jittery", "Antsy", "Restless", "On edge"],
  ["Uneasy", "Unsettled", "Apprehensive", "Wary", "Hesitant"],
  ["Dreading", "Apprehensive", "Intimidated", "Unprepared", "Nervous"],
  ["Startled", "Rattled", "Shocked", "Stunned", "Horrified"],
  ["Guarded", "Suspicious", "Defensive", "Wary", "Distant"],
  ["Cautious", "Hesitant", "Skeptical", "Doubtful", "Uncertain"],
  ["Furious", "Angry", "Mad", "Outraged", "Hostile"],
  ["Angry", "Mad", "Frustrated", "Exasperated", "Fed up"],
  ["Outraged", "Indignant", "Offended", "Disrespected", "Appalled"],
  ["Bitter", "Resentful", "Betrayed", "Vengeful", "Hostile"],
  ["Annoyed", "Irritated", "Grumpy", "Impatient", "Frustrated"],
  ["Disgusted", "Appalled", "Horrified", "Offended"],
  ["Jealous", "Insecure", "Threatened", "Resentful", "Bitter"],
  ["Embarrassed", "Mortified", "Humiliated", "Ashamed", "Exposed", "Judged"],
  ["Awkward", "Self-conscious", "Sheepish", "Shy", "Flustered", "Foolish"],
  ["Insecure", "Inadequate", "Inferior", "Unworthy", "Self-conscious"],
  ["Unworthy", "Unlovable", "Unwanted", "Rejected"],
  ["Uncomfortable", "Awkward", "Unwelcome", "Alienated", "Self-conscious"],
  ["Overwhelmed", "Stressed", "Burdened", "Frazzled", "Frantic"],
  ["Stressed", "Pressured", "Rushed", "Overworked", "Burdened"],
  ["Rushed", "Frantic", "Frazzled", "Impatient", "Unprepared"],
  ["Overstimulated", "Overwhelmed", "Agitated", "Frazzled", "Drained"],
  ["Burnt out", "Exhausted", "Depleted", "Overworked", "Drained"],
  ["Exhausted", "Drained", "Tired", "Weary", "Depleted"],
  ["Tired", "Sluggish", "Lethargic", "Weary", "Sleepy"],
  ["Sleepy", "Groggy", "Foggy", "Dazed", "Distracted"],
  ["Unwell", "Lethargic", "Groggy", "Foggy"],
  ["Rested", "Refreshed", "Recharged", "Renewed", "Energized"],
  ["Lonely", "Isolated", "Disconnected", "Alienated", "Left out"],
  ["Ignored", "Invisible", "Neglected", "Unappreciated", "Dismissed"],
  ["Rejected", "Left out", "Unwelcome", "Unwanted", "Abandoned"],
  ["Misunderstood", "Dismissed", "Unsupported", "Unappreciated", "Judged"],
  ["Withdrawn", "Distant", "Detached", "Disconnected", "Guarded"],
  ["Flat", "Meh", "Bored", "Indifferent", "Okay"],
  ["Apathetic", "Indifferent", "Numb", "Unmotivated", "Detached"],
  ["Unmotivated", "Uninspired", "Aimless", "Unfulfilled", "Bored"],
  ["Okay", "Meh", "Steady", "Calm", "Ambivalent"],
  ["Distracted", "Preoccupied", "Foggy", "Dazed", "Restless"],
  ["Confused", "Puzzled", "Disoriented", "Uncertain", "Lost"],
  ["Torn", "Conflicted", "Ambivalent", "Mixed", "Uncertain"],
  ["Bittersweet", "Nostalgic", "Wistful", "Sentimental", "Moved", "Tender"],
  ["Surprised", "Astonished", "Stunned", "Amazed", "Shocked"],
  ["Pensive", "Thoughtful", "Reflective", "Introspective", "Earnest"],
  ["Present", "Grounded", "Calm", "Steady", "Balanced"],
  ["Accepting", "Sympathetic", "Compassionate", "Forgiving", "Patient"],
  ["Calm", "Relaxed", "Mellow", "Patient", "Peaceful"],
  ["Peaceful", "Serene", "Calm", "Blissful", "Content"],
  ["Steady", "Balanced", "Grounded", "Secure", "Confident"],
  ["Safe", "Secure", "Reassured", "Comforted", "Supported", "Trusting"],
  ["Comfortable", "Cozy", "Content", "Warm", "Cared for", "Safe"],
  ["Relieved", "Free", "Carefree", "Lighthearted", "Unbothered", "Reassured"],
  ["Curious", "Interested", "Intrigued", "Engaged", "Fascinated"],
  ["Fascinated", "Captivated", "Enchanted", "Intrigued", "Awed"],
  ["Awed", "Amazed", "Astonished", "Impressed", "Moved"],
  ["Focused", "Engaged", "Productive", "Present", "Alert"],
  ["Determined", "Committed", "Resilient", "Strong", "Unstoppable"],
  ["Motivated", "Ambitious", "Purposeful", "Passionate", "Committed"],
  ["Ready", "Prepared", "Capable", "Confident", "Focused"],
  ["Challenged", "Competitive", "Determined", "Resilient", "Brave"],
  ["Hopeful", "Optimistic", "Positive", "Encouraged", "Upbeat"],
  ["Eager", "Excited", "Enthusiastic", "Hopeful", "Ready", "Curious"],
  ["Renewed", "Uplifted", "Inspired", "Refreshed", "Encouraged"],
  ["Faithful", "Hopeful", "Trusting", "Grateful", "Blessed"],
  ["Confident", "Capable", "Strong", "Empowered", "Independent"],
  ["Worthy", "Accepted", "Secure", "Confident", "Valued"],
  ["Brave", "Fearless", "Bold", "Adventurous", "Resilient"],
  ["Proud", "Accomplished", "Successful", "Satisfied", "Fulfilled"],
  ["Triumphant", "Unstoppable", "Elated", "Successful", "Proud"],
  ["Valued", "Recognized", "Validated", "Appreciated", "Respected"],
  ["Connected", "Close", "Included", "Accepted", "Sociable"],
  ["Supported", "Understood", "Seen", "Cared for", "Validated"],
  ["Loved", "Cherished", "Adored", "Wanted", "Appreciated"],
  ["Loving", "Affectionate", "Warm", "Compassionate", "Attached"],
  ["In love", "Smitten", "Romantic", "Flirty", "Affectionate"],
  ["Grateful", "Blessed", "Touched", "Moved", "Appreciated"],
  ["Forgiving", "Accepting", "Compassionate", "Peaceful"],
  ["Sociable", "Playful", "Warm", "Included", "Upbeat"],
  ["Happy", "Glad", "Cheerful", "Upbeat", "Pleased"],
  ["Joyful", "Happy", "Delighted", "Elated", "Cheerful"],
  ["Delighted", "Pleased", "Amused", "Glad", "Enchanted"],
  ["Silly", "Goofy", "Playful", "Amused", "Giddy"],
  ["Giddy", "Bubbly", "Cheerful", "Playful"],
  ["Overjoyed", "Ecstatic", "Euphoric", "Elated", "Blissful"],
  ["Content", "Satisfied", "Fulfilled", "Pleased", "Present"],
  ["Energized", "Alive", "Refreshed", "Recharged", "Alert"],
  ["Excited", "Hyped", "Pumped", "Stoked", "Thrilled"],
  ["Thrilled", "Exhilarated", "Ecstatic", "Enthusiastic", "Passionate"],
  ["Adventurous", "Spontaneous", "Bold", "Free", "Curious"],
  ["Creative", "Inspired", "Curious", "Passionate", "Engaged"],
] as const satisfies readonly (readonly FeelingWord[])[];

// Strong bridges connect specific meanings across neighborhoods. The first word
// connects to each subsequent word, in both directions (not a parent/child tree).
export const feelingBridges = [
  [
    "Devastated",
    "Heartbroken",
    "Grieving",
    "Hopeless",
    "Crushed",
    "Shattered",
    "Miserable",
    "Despairing",
    "Hurt",
    "Sad",
    "Disappointed",
    "Defeated",
    "Overwhelmed",
  ],
  ["Sad", "Down", "Sorrowful", "Tearful", "Unhappy"],
  ["Anxious", "Worried", "Stressed", "On edge", "Apprehensive", "Nervous"],
  [
    "Overwhelmed",
    "Overstimulated",
    "Stressed",
    "Helpless",
    "Burdened",
    "Frazzled",
  ],
  [
    "Burnt out",
    "Exhausted",
    "Depleted",
    "Unmotivated",
    "Drained",
    "Overworked",
  ],
  ["Lonely", "Disconnected", "Homesick", "Isolated", "Left out", "Invisible"],
  ["Angry", "Frustrated", "Furious", "Resentful", "Betrayed", "Disrespected"],
  [
    "Insecure",
    "Self-conscious",
    "Inadequate",
    "Vulnerable",
    "Jealous",
    "Judged",
  ],
  ["Bittersweet", "Nostalgic", "Wistful", "Mixed", "Sentimental", "Moved"],
  ["Calm", "Relaxed", "Grounded", "Peaceful", "Safe", "Content"],
  ["Happy", "Joyful", "Content", "Cheerful", "Delighted", "Grateful"],
  [
    "Proud",
    "Accomplished",
    "Fulfilled",
    "Confident",
    "Recognized",
    "Triumphant",
  ],
  ["Excited", "Eager", "Enthusiastic", "Thrilled", "Inspired", "Hyped"],
  ["Loved", "Connected", "Cherished", "Supported", "Accepted", "Cared for"],
  ["Grateful", "Blessed", "Touched", "Loved", "Fulfilled"],
  ["Hopeful", "Optimistic", "Encouraged", "Uplifted", "Renewed"],
  ["Earnest", "Determined", "Committed", "Eager"],
] as const satisfies readonly (readonly FeelingWord[])[];
